version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    networks:
      - metanet1
    # healthcheck:
    #   test: curl --fail -I http://localhost:3000/api/health || exit 1
    #   interval: 15s
    #   timeout: 5s
    #   retries: 5

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    hostname: postgres
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - metanet1

networks:
  metanet1:
    driver: bridge
