version: 2

sources:
  - name: postgres
    config:
      enabled: true
    database: postgres
    schema: bronze
    tables:
      - name: categories
      - name: customer_customer_demo
      - name: customer_demographics
      - name: customers
      - name: employee_territories
      - name: employees
      - name: order_details
      - name: orders
      - name: products
      - name: shippers
      - name: suppliers
      - name: territories
      - name: us_states

        