version: "3.1"

services:
  metabase:
      image: metabase/metabase:v0.46.6.4
      container_name: metabase
      volumes:
        - ./include/metabase-data:/metabase-data
      ports:
        - 3000:3000
      environment:
        - MB_DB_FILE=/metabase-data/metabase.db
      restart: always
      networks:
        - airflow_cad268_airflow
      depends_on:
        - airflow_cad268-postgres-1
        
networks:
  airflow_cad268_airflow:
    external: True