version: 3

datawarehouse:
  target: dev
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DB') }}"
      host: "{{ env_var('POSTGRES_HOST') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
